name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Flowbaby
title: "[Bug]: "
labels: ["type: bug", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

        **⚠️ Privacy reminder**: Please do not include API keys, tokens, internal URLs, or other sensitive information in your report.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Open VS Code...
        2. Run command '...'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Flowbaby Version
      description: What version of Flowbaby are you using?
      options:
        - Latest (from VS Code Marketplace)
        - Pre-release / Insider
        - I don't know
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: "Run `code --version` in your terminal to find this."
      placeholder: "e.g., 1.85.0"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Error Messages
      description: |
        If applicable, paste any relevant logs or error messages.
        Check the Flowbaby output channel in VS Code: View → Output → Select "Flowbaby" from the dropdown.
      placeholder: Paste logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem.
      placeholder: Any additional information...
    validations:
      required: false

  - type: textarea
    id: internal-reference
    attributes:
      label: Internal Reference (Maintainers Only)
      description: |
        For maintainers: Link to related internal issues if applicable.
        Format: `lsalsich/flowbaby#123`
      placeholder: "lsalsich/flowbaby#..."
    validations:
      required: false
